### ISSUE TITLE
Error depois de logar

### ISSUE THREAD

**Issue by DWoonD** [sio-iago/project-manager#6]
Fiz o login e tudo que estava escrito no readme e depois que loguei deu esse erro

Slim Application Error
The application could not run because of the following error:

Details

Type: Twig_Error_Runtime
Message: An exception has been thrown during the rendering of a template ("Entity of type 'ProjectManager\Projects\Model\Project' for IDs id(6) was not found") in "@Dashboard/index.twig" at line 91.
File: C:\xampp\htdocs\freela\vendor\twig\twig\lib\Twig\Template.php
Line: 182
Trace

#0 C:\xampp\htdocs\freela\vendor\twig\twig\lib\Twig\Environment.php(403) : eval()'d code(225): Twig_Template->displayBlock('content', Array, Array)
#1 C:\xampp\htdocs\freela\vendor\twig\twig\lib\Twig\Template.php(381): __TwigTemplate_a6a3c3cb17077ffe9c16d1839ab3f76d780e94cda304ffdf042d5bc0c1f920d6->doDisplay(Array, Array)
#2 C:\xampp\htdocs\freela\vendor\twig\twig\lib\Twig\Template.php(355): Twig_Template->displayWithErrorHandling(Array, Array)
#3 C:\xampp\htdocs\freela\vendor\twig\twig\lib\Twig\Environment.php(403) : eval()'d code(24): Twig_Template->display(Array, Array)
#4 C:\xampp\htdocs\freela\vendor\twig\twig\lib\Twig\Template.php(381): __TwigTemplate_bdaa95271e68365471c9cc8464ce29466fb452b56ad5455146ff860d3bd30779->doDisplay(Array, Array)
#5 C:\xampp\htdocs\freela\vendor\twig\twig\lib\Twig\Template.php(355): Twig_Template->displayWithErrorHandling(Array, Array)
#6 C:\xampp\htdocs\freela\vendor\twig\twig\lib\Twig\Template.php(366): Twig_Template->display(Array)
#7 C:\xampp\htdocs\freela\src\SIOFramework\Common\Controller\DefaultController.php(75): Twig_Template->render(Array)
#8 C:\xampp\htdocs\freela\src\ProjectManager\Dashboard\Controller\DashboardController.php(57): SIOFramework\Common\Controller\DefaultController->render('@Dashboard/inde...', Array)
#9 C:\xampp\htdocs\freela\src\ProjectManager\Dashboard\conf\routes.php(7): ProjectManager\Dashboard\Controller\DashboardController->index()
#10 [internal function]: {closure}()
#11 C:\xampp\htdocs\freela\vendor\slim\slim\Slim\Route.php(468): call_user_func_array(Object(Closure), Array)
#12 C:\xampp\htdocs\freela\vendor\slim\slim\Slim\Slim.php(1357): Slim\Route->dispatch()
#13 C:\xampp\htdocs\freela\vendor\slim\slim\Slim\Middleware\Flash.php(85): Slim\Slim->call()
#14 C:\xampp\htdocs\freela\vendor\slim\slim\Slim\Middleware\MethodOverride.php(92): Slim\Middleware\Flash->call()
#15 C:\xampp\htdocs\freela\vendor\slim\slim\Slim\Middleware\PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#16 C:\xampp\htdocs\freela\vendor\slim\slim\Slim\Slim.php(1302): Slim\Middleware\PrettyExceptions->call()
#17 C:\xampp\htdocs\freela\index.php(11): Slim\Slim->run()
#18 {main}

Quando rodei o php no cmd do windows foi assim

C:\xampp\htdocs\freela>php vendor/bin/doctrine orm:schema-tool:update --force --dump-sql

dir=$(d=${0%[/\\]*}; cd "$d"; cd "../doctrine/orm/bin" && pwd)

# See if we are running in Cygwin by checking for cygpath program
if command -v 'cygpath' >/dev/null 2>&1; then
        # Cygwin paths start with /cygdrive/ which will break windows PHP,
        # so we need to translate the dir path to windows format. However
        # we could be using cygwin PHP which does not require this, so we
        # test if the path to PHP starts with /cygdrive/ rather than /usr/bin
        if [[ $(which php) == /cygdrive/* ]]; then
                dir=$(cygpath -m "$dir");
        fi
fi

dir=$(echo $dir | sed 's/ /\ /g')
"${dir}/doctrine" "$@"

Nunca usei composer e talz, é isso mesmo? uso windows, criei o banco de dados mysql, estou usando o xampp, acho que é isso

**Comment by sio-iago** [comment]
Antes de tudo, vc baixou o branch master ou alguma release?

**Comment by sio-iago** [comment]
Vou tentar instalar aqui no Windows e ver o que dá

**Comment by sio-iago** [comment]
Rode, por favor, o seguinte SQL e veja se a funciona:

`delete from pm_product where project_id != 8`

O schema.sql está inconsistente. Mudarei e subirei uma atualização.
Obrigado por apontar o erro.

**Comment by sio-iago** [comment]
PS: Estarei subindo uma release nova com um instalador, estilo OpenCart, WordPress, etc... pra facilitar ainda mais a vida. Deixar o sistema plug-n-play.

**Comment by DWoonD** [comment]
Rodei a query query que vc passou e funcionou sim man, mas ainda tem alguns erros em projeto, acredito que seja por causa das tabelas mesmo, quando der uma atualizada avisa, sem pressa, e se ficar igual o wp vai ser massa ^^

Obrigado pelo help

**Comment by sio-iago** [comment]
Cara, sinta-se a vontade pra apontar quaisquer erros.
Eu to pra lançar um vídeo dando uma visão geral do sistema e tal, então alguns erros que vc pode estar tendo são

1. A data ainda está em formato mm/dd/yyyy, padrão enUS.
2. Acessando do iOS ou Android, o datepicker do sistema não funciona.
3. O sistema passou por uma repaginada no layout, então o módulo de cliente, por exemplo, está ruim ainda.

Quaisquer outros erros, pode ir listando aqui ou abrindo outros Issues que eu vou consertando. Sinta-se a vontade em colaborar tanto com feedback quanto em código, caso queira.

**Comment by DWoonD** [comment]
Certo, vou tentar entender melhor o sistema como um todo, e caso consiga contribuir com código eu faço um fork e um pull, mas nunca usei essas tecnologias que você usa, twig e doctrine, mas vou dar uma estudada, mas conforme for encontrando algo vou listando aqui.

1 - Erro ao criar ou salvar um projeto
Fatal error: Uncaught Error: Call to a member function format() on boolean in C:\xampp\htdocs\freela\vendor\doctrine\dbal\lib\Doctrine\DBAL\Types\DateType.php:53 Stack trace: #0 C:\xampp\htdocs\freela\vendor\doctrine\dbal\lib\Doctrine\DBAL\Statement.php(114): Doctrine\DBAL\Types\DateType->convertToDatabaseValue(false, Object(Doctrine\DBAL\Platforms\MySqlPlatform)) #1 C:\xampp\htdocs\freela\vendor\doctrine\orm\lib\Doctrine\ORM\Persisters\Entity\BasicEntityPersister.php(277): Doctrine\DBAL\Statement->bindValue(3, false, Object(Doctrine\DBAL\Types\DateType)) #2 C:\xampp\htdocs\freela\vendor\doctrine\orm\lib\Doctrine\ORM\UnitOfWork.php(1018): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->executeInserts() #3 C:\xampp\htdocs\freela\vendor\doctrine\orm\lib\Doctrine\ORM\UnitOfWork.php(378): Doctrine\ORM\UnitOfWork->executeInserts(Object(Doctrine\ORM\Mapping\ClassMetadata)) #4 C:\xampp\htdocs\freela\vendor\doctrine\orm\lib\Doctrine\ORM\EntityManager.php(356): Doctrine\ORM\UnitOfWork->commit(NULL) #5 C:\xampp\htdocs\freela\s in C:\xampp\htdocs\freela\vendor\doctrine\dbal\lib\Doctrine\DBAL\Types\DateType.php on line 53

2 - Erro quando clica em allocation

Slim Application Error
The application could not run because of the following error:

Details

Type: Doctrine\DBAL\Exception\TableNotFoundException
Message: An exception occurred while executing 'SELECT t0.id AS id_1, t0.description AS description_2, t0.value AS value_3, t0.date_worked AS date_worked_4, t0.product_id AS product_id_5, t0.user_id AS user_id_6 FROM pm_allocation t0 ORDER BY t0.date_worked DESC': SQLSTATE[42S02]: Base table or view not found: 1146 Table 'freela.pm_allocation' doesn't exist
File: C:\xampp\htdocs\freela\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php
Line: 53
Trace

#0 C:\xampp\htdocs\freela\vendor\doctrine\dbal\lib\Doctrine\DBAL\DBALException.php(116): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 C:\xampp\htdocs\freela\vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php(836): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT t0.id AS...', Array)
#2 C:\xampp\htdocs\freela\vendor\doctrine\orm\lib\Doctrine\ORM\Persisters\Entity\BasicEntityPersister.php(884): Doctrine\DBAL\Connection->executeQuery('SELECT t0.id AS...', Array, Array)
#3 C:\xampp\htdocs\freela\vendor\doctrine\orm\lib\Doctrine\ORM\EntityRepository.php(181): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->loadAll(Array, Array, NULL, NULL)
#4 C:\xampp\htdocs\freela\src\SIOFramework\Common\Factory\DoctrineFactory.php(52): Doctrine\ORM\EntityRepository->findBy(Array, Array, NULL, NULL)
#5 C:\xampp\htdocs\freela\src\ProjectManager\Projects\Controller\AllocationController.php(18): SIOFramework\Common\Factory\DoctrineFactory->selectAll('Projects:Alloca...', Array, Array)
#6 C:\xampp\htdocs\freela\src\ProjectManager\Projects\conf\routes.php(85): ProjectManager\Projects\Controller\AllocationController->allocationOverview()
#7 [internal function]: {closure}()
#8 C:\xampp\htdocs\freela\vendor\slim\slim\Slim\Route.php(468): call_user_func_array(Object(Closure), Array)
#9 C:\xampp\htdocs\freela\vendor\slim\slim\Slim\Slim.php(1357): Slim\Route->dispatch()
#10 C:\xampp\htdocs\freela\vendor\slim\slim\Slim\Middleware\Flash.php(85): Slim\Slim->call()
#11 C:\xampp\htdocs\freela\vendor\slim\slim\Slim\Middleware\MethodOverride.php(92): Slim\Middleware\Flash->call()
#12 C:\xampp\htdocs\freela\vendor\slim\slim\Slim\Middleware\PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#13 C:\xampp\htdocs\freela\vendor\slim\slim\Slim\Slim.php(1302): Slim\Middleware\PrettyExceptions->call()
#14 C:\xampp\htdocs\freela\index.php(11): Slim\Slim->run()
#15 {main}

Esse acredito que seja erro no banco, bom conforme eu tiver um tempo vou tentar analisar tudo man, obrigado por tudo, e malz pelo horario x.x

**Comment by sio-iago** [comment]
Tranquilo. O erro 1 é pq o formato da data está em mês/dia/ano, então se não passar certinho o sistema chia na hora de persistir no banco. O erro 2 é pq, por algum motivo, quando executou o comando do doctrine ele n criou a tabela. Tenta rodar o comando com --force, sem o --dump-sql que provavelmente vai.

**Comment by sio-iago** [comment]
@DWoonD o instalador está pronto.
Postarei uma tag com o sistema pronto para uso e instruções da instalação, sem necessidade de composer, configurar arquivos, etc.
